main: ca.evannosich.Bakery.Bakery
name: Bakery
api-version: 1.14
version: 1.0
author: Evan Nosich (ComradeBushtail)
description: A plugin that allows players to smelt wheat in a furnace to create bread.
