main: ca.evannosich.Bakery.Bakery
name: Bakery
api-version: 1.14
version: 1.1
author: Evan Nosich (ComradeBushtail)
description: A plugin that allows players to smelt wheat in a furnace and smoker to create bread.
